#pragma once

typedef enum INTER_ERROR
{
	// used by Chen Yi
	ERROR_SEG1 = -10000,
	ERROR_DB_CONNECT = -9999,
	ERROR_DOGSERVER_CONNECT,
	ERROR_DGUPDATESERVER_CONNECT,
	ERROR_DGLOGSERVER_CONNECT,
	ERROR_DGFILEACCREDITSERVER_CONNECT,
	ERROR_DGFILEUPLOADSERVER_CONNECT,
	ERROR_DGFLOWSETFILE_NOTFOUND,
	ERROR_REGISTER_NOTFOUND,
	ERROR_DGCLIENTU_CONNECT,

	// used by Li Yelong
	ERROR_LOCAL_DB_CONNECT = -8000,
	

	// used by Li Xiaochun
	ERROR_SEG3 = -6000,
	ERROR_OPEN_REGISTER_FAILED,
	ERROR_QUERY_WFURL_FAILED,
	ERROR_URL_NOT_VALID,
	ERROR_INVALID_INPUT_PARAM,


	// used by Tan Meng-en
	ERROR_SEG4 = -4000,

	// used by Zhang Wang
	ERROR_SEG5 = -3000,
	
 
} DG_ErrorCode;
