// HTFileTransferSystemService.idl : IDL source for HTFileTransferSystemService
//

// This file will be processed by the MIDL tool to
// produce the type library (HTFileTransferSystemService.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(90989EEF-A18B-483D-98F7-987C80FFAC77),
	version(1.0),
	helpstring("HTFileTransferSystemService 1.0 Type Library")
]
library HTFileTransferSystemServiceLib
{
	importlib("stdole2.tlb");
};
